- common.h
- kernel32.cpp
These functions are needed for mwldeppc.exe to work.
Note that these implementations are rather dummy in nature and not fully compliant to the Windows API.
> implement SetEndOfFile, CreateDirectoryA, RemoveDirectoryA, SetFileAttributesA

- CMakeLists.txt
- cmake/FindFilesystem.cmake
- loader.cpp
This should handle the issue of needing to explicitly link against a separate library for std::filesystem support. IMO this is the easiest way to do this, I've used this module in other projects and it works quite well. I've dropped it in a `cmake/` subfolder verbatim, but it can be consumed in other ways if you prefer, such as a git submodule or PMM package.
> Explicitly link std::filesystem as needed

- dll/kernel32.cpp
When the output buffer size is too small, GetCurrentDirectory does nothing and simply returns the larger required size.
https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getcurrentdirectory#return-value
Needed to run Code Warrior 4 mwcc.exe with no arguments, displaying usage/help message.
(Still unable to compile/preprocess with CW4 mwcc.exe)
> Handle GetCurrentDirectory required buffer size return value

- .github/workflows/ci.yml
- Dockerfile
This updates the Dockerfile to build a fully static i386 binary using Alpine Linux & musl libc.
This allows easily using it on non-x86 architectures via `qemu-i386`, and avoids depending on the installed libstdc++ version.
The release binary grows from ~0.8MB to ~1.8MB, but I think the benefits are more than worth it.
As a bonus, the resulting Docker image is nearly 20x smaller:
```
REPOSITORY               TAG       IMAGE ID       CREATED          SIZE
wibo                     latest    e033ebc1e00e   15 minutes ago   8.86MB
ghcr.io/decompals/wibo   latest    74a67030a46e   3 weeks ago      157MB
```
> Build static binary

- main.cpp
Before, argv[0] was a relative path with forward slashes, which MWCC didn't like.
> Pass absolute path to exe in argv[0]

- common.h
- dll/kernel32.cpp
- files.cpp
- files.h
`callee_pop_aggregate_return(0)` isn't actually necessary for any of our functions (yet), but matches the Windows x86 ABI (https://gcc.gnu.org/onlinedocs/gcc/x86-Function-Attributes.html)
> Various fixes for mwcc/mwld

- dll/kernel32.cpp
- main.cpp
As per the title. Fixes #21.
Right now, this takes the simplest (if brute force-iest) approach: it maps the upper 2GB of program memory to ensure libc can't allocate anything there.
(If it turns out this breaks anything, happy to switch this out for a smarter option :))
> Force VirtualAlloc allocations to fall below the 2GB mark

- .github/workflows/ci.yml
- dll/kernel32.cpp
Fixes #17 
- Implements FindFirstFileExA and InterlockedExchange 
- Have LCMapStringW bluff and return success in all cases
- ~Have RtlUnwind carry on silently in the case of a longjmp. As far as I can tell, armcc only uses this to jump to a function that prints timing information and closes files up before exiting, and will happily exit successfully with this stubbed.~ Stub RtlUnwind, and print a warning.
> Add armcc support

- .github/workflows/ci.yml
- .github/workflows/docker.yaml
I've learnt this week that I've been doing docker deployments from GHA wrong. We should be using the `secrets.GITHUB_TOKEN` rather than my own PAT :) Also taken the opportunity to bump the various deps.
> Use correct token for docker deployment

- .gitignore
- CMakeLists.txt
- common.h
- dll/kernel32.cpp
- handles.h
- main.cpp
- processes.cpp
- processes.h
(and maybe some other things, too!)
This PR implements a bare-bones CreateProcessA, WaitForSingleObject, and GetExitCodeProcess - enough to start a process, wait for it to exit, and check it quit okay.
In order to achieve this, it introduces processes as a new type of handle. As far as I can tell, we've never tagged metadata along with handles before - more than happy for feedback on the approach taken.
> Implement enough process handling logic to make psyq4.0 happy

- CMakeLists.txt
- main.cpp
- ~~Adds `procLine.reserve(0x8000);` to ensure that the `std::string` doesn't cause memory allocation between reading `/proc/self/maps` and the `mmap` calls.~~ Replaced with Linux syscalls and stack buffer to avoid any allocations.
- ~~Replaces `MAP_FIXED` with `MAP_FIXED_NOREPLACE` (Linux 4.17+) to ensure that we bail if our mapping would overwrite an existing one.~~
- Moves this logic into a separate method `blockUpper2GB` to simplify cleanup.
- Adds `-fno-pie -no-pie` cflags to ensure that we're not using PIE. (Probably unnecessary, but seems good)
> Ensure we don't reallocate during 2GB address space block

- .github/workflows/ci.yml
- Dockerfile
Adds an unstripped `wibo_debug` binary ( `-O0 -g`) to build artifacts and releases for use with a debugger.
> Build a debug binary as well

- dll/kernel32.cpp
I dunno if there is a better way than copy/paste to support these?
Closes #50:
```
$ ~/github/wibo/build/wibo armcc.exe
Product: unknown
Component: unknown
Tool: armcc [5040081]
Usage:         armcc [options] file1 file2 ... filen
Main options:
--arm          Generate ARM code
--thumb        Generate Thumb code
--c90          Switch to C mode (default for .c files)
--cpp          Switch to C++ mode (default for .cpp files)
-O0            Minimum optimization
-O1            Restricted optimization for debugging
-O2            High optimization
-O3            Maximum optimization
-Ospace        Optimize for codesize
-Otime         Optimize for maximum performance
--cpu <cpu>    Select CPU to generate code for
--cpu list     Output a list of all the selectable CPUs
--device <dev> Set the …
```
> Add Fibre local storage (Fls*) functions for armcc

- dll/kernel32.cpp
- dll/version.cpp
> Support ProDC NgcAs.exe

- dll/kernel32.cpp
Before this change, `dwCreationDisposition` parameter of `CreateFileA` was ignored by wibo. However, it turns out that `PSYLINK.EXE` in PsyQ 4.4 sometimes depends on correct handling of that parameter.
When building overlays with `PSYLINK.EXE`, it sometimes opens the resulting overlay file the second time, with `OPEN_EXISTING` creation disposition (as opposed to `TRUNCATE_EXISTING`). Before the change, wibo opened that file with `fopen(..., "wb+")` which truncated the file even though `OPEN_EXISTING` (non-truncating) was requested. This affected [mgs_reversing](https://github.com/foxdieteam/mgs_reversing), where one of the overlays (`camera.bin`) was built incorrectly when using wibo (worked correctly on Windows or with wine).
This PR adds proper handling of `dwCreationDisposition` …
> Handle dwCreationDisposition in CreateFileA to fix PSYLINK

- CMakeLists.txt
- main.cpp
This PR * very hackily * fixes #64 and the issues with mwldeppc in the xenoblade CI by allowing writes to the blocker regions we use to prevent libc from allocating in the upper 2GB of memory.
See discussion from https://discord.com/channels/710646040331681844/991954626448457828/1188187281056600094 onwards - this is only intended as a temporary solution, to tide over programs this breaks until the implementation of a custom heap allocator.
> [TEMPORARY FIX] Fix issues with the stack not being resized correctly

- dll/kernel32.cpp
Defaults to `/tmp` but can be overridden with WIBO_TMP_DIR environment variable, e.g.
```
WIBO_TMP_DIR=z:\\home\\mark ~/github/wibo/build/wibo pspsnc.exe -S test.c -o test.s
```
This function is needed to run `pspsnc.exe`.
> Add GetTempPathA

- dll/kernel32.cpp
Those fixes are required to get the GCC SN 2.73a for PS2 compiler working on wibo.
- The `FindFirstFileA` fix handles the case where the passed path is a relative path with no parent (ie `include`).
- The fix treats said empty parent as the current directory (`.`)
- The `str_for_LCType` fix adds a few extra types and changes the function to return an empty string for unrecognized `LCType`s.
- For whatever reason `as.exe` was requesting all kinds of whacky info I'm pretty sure it wasn't going to use (why it wanted stuff like the locale currency symbol?)
> Fix `FindFirstFileA` failing due to an empty parent and add locale `LCType` stubs

- dll/kernel32.cpp
More fixes to get GCC SN 2.73a for PS2 compiler working on wibo. This one seems to be required only when passing `-g3`
This time related functions are used by `cpp.exe` to declare the `__DATE__` and `__TIME__` macros.
> Proper implementation for `GetSystemTime` and `GetLocalTime`

- dll/kernel32.cpp
- files.cpp
Adds support to handle directories with trailing periods (ie `include/.`) passed to `FindFirstFileA` and family.
I couldn't find docs on how the function should behave in this case (https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfilea), but assuming it means "find anything on the passed directory" makes the program happy.
This was needed by "GCC 2.95.3 SN 1.14's `cpp.exe`"
I also added an assert in `FindFirstFileA` to check for wildcards and a few other unrelated logs. I can remove them if preferred.
> Add trailing periods support to `FindFirstFileA`

- dll/kernel32.cpp
- files.cpp
This PR checks if the path passed into pathFromWindows starts and ends with escaped quotation marks, and if yes, remove those from the string so that the rest of the parsing code runs correctly.
(This fixes an issue with SHC putting quotation marks around the path arguments passed into its sub-processes)
> Added quotation mark check in files::pathFromWindows

- dll/kernel32.cpp
> Move empty pattern check into while loop

- CMakeLists.txt
- Dockerfile
- dll/kernel32.cpp
musl libc's malloc is notoriously slow, and that ends up being what we're using when compiling the static release binaries. Instead, we can integrate [mimalloc](https://github.com/microsoft/mimalloc), a very fast and robust modern allocator. The dependency is fetched using CMake's FetchContent. Linking `mimalloc-static` automatically overrides C++ new/delete, as well as malloc/realloc/etc.
When testing, this cut almost a minute off of ac-decomp's build time:
```
real	2m40.719s
user	38m12.308s
sys	14m58.701s
```
to
```
real	1m50.328s
user	25m22.266s
sys	10m53.724s
```
In `kernel32.cpp`, we now explicitly use aligned allocations of 8 to match the described behavior of [GlobalAlloc](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-globalalloc) and the like.
This …
> Integrate mimalloc

- .github/workflows/ci.yml
- AGENTS.md
- CMakeLists.txt
- Dockerfile
- Dockerfile.ubuntu
- README.md
- src/main.cpp
- src/version_info.h.in
Example output:
```console
$ wibo
wibo 1.0.0-alpha.1
Usage:
wibo [options] <program.exe> [arguments...]
wibo path [subcommand options] <path> [path...]
General Options:
-h, --help            Show this help message and exit
-V, --version         Show version information and exit
Runtime Options:
-C, --chdir DIR       Change working directory before launching the program
-D, --debug           Enable debug logging (same as WIBO_DEBUG=1)
--cmdline STRING  Use STRING as the exact guest command line
(includes the program name, e.g. "test.exe a b c")
--                Stop option parsing; following arguments are used
verbatim as the guest command line, including the
program name
Subcommands:
path                  Convert between host and Windows-style paths
(see 'wibo path --help' for details) …
```
> Revamp CLI --help and add --version
